SET NAMES utf8mb4;
SET time_zone = '+00:00';

ALTER TABLE media_assignments
  MODIFY COLUMN entity_type
    ENUM('MENU','MENU_CATEGORY_ASSIGNMENT','MENU_ITEM_ASSIGNMENT','MENU_ITEM_VARIANT','MENU_ITEM','COUNTER','PRINTING_GROUP','RECIPE')
    NOT NULL;
