import { useMemo, useState } from 'react';
import { BillingStatus, Capability, type BillingExportDto } from '@menuboard/shared';
import { CircleCheckIcon, CircleXIcon, EyeIcon } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { SelectField } from '@/components/form/fields';
import { RowActions } from '@/components/RowActions';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { DataTable, type DataTableColumn } from '../../components/DataTable/DataTable';
import { useViewMode } from '../../components/DataTable/gridState';
import { EntityCardGrid } from '../../components/EntityCardGrid';
import { ListToolbar } from '../../components/ListToolbar';
import { PageHeader } from '../../components/ui/PageHeader';
import { StatusChip } from '../../components/StatusChip';
import { IfCapable } from '../../services/CapabilityGate';
import { useBillingList, useUpdateBillingStatus } from '../../hooks/useAdmin';
import { enumOptions } from '@/lib/options';
import { notify } from '@/lib/notify';
import { GenerateBillingModal } from './GenerateBillingModal';
import { SnapshotViewerModal } from './SnapshotViewerModal';

export function BillingPage(): JSX.Element {
  const [status, setStatus] = useState<BillingStatus | ''>('');
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);
  const [view, setView] = useViewMode('billing');
  const [generating, setGenerating] = useState(false);
  const [viewing, setViewing] = useState<string | null>(null);
  const [action, setAction] = useState<{ export: BillingExportDto; status: BillingStatus } | null>(
    null,
  );

  const query = useMemo(
    () => ({ status: status || undefined, page, pageSize }),
    [status, page, pageSize],
  );
  const { data, isLoading } = useBillingList(query);
  const updateStatus = useUpdateBillingStatus();

  const columns: DataTableColumn<BillingExportDto>[] = [
    { field: 'billingVersion', headerName: 'Version', width: 90, align: 'right' },
    {
      field: 'boardId',
      headerName: 'Scope',
      width: 130,
      valueGetter: (r) => (r.boardId ? 'Single board' : 'All boards'),
    },
    { field: 'periodFrom', headerName: 'From', width: 110 },
    { field: 'periodTo', headerName: 'To', width: 110 },
    {
      field: 'status',
      headerName: 'Status',
      width: 120,
      renderCell: (r) => <StatusChip status={r.status} />,
    },
    { field: 'totalOrders', headerName: 'Orders', width: 90, align: 'right' },
    { field: 'totalPax', headerName: 'Pax', width: 90, align: 'right' },
    {
      field: 'generatedByName',
      headerName: 'Generated by',
      width: 150,
      valueGetter: (r) => r.generatedByName ?? '—',
    },
    {
      field: 'generatedAt',
      headerName: 'Generated at',
      width: 170,
      valueGetter: (r) => new Date(r.generatedAt).toLocaleString(),
    },
    { field: 'checksum', headerName: 'Checksum', width: 220 },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 130,
      sortable: false,
      align: 'right',
      alwaysVisible: true,
      renderCell: (r) => (
        <RowActions>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon-sm"
                onClick={() => setViewing(r.id)}
                aria-label={`View billing snapshot v${r.billingVersion}`}
              >
                <EyeIcon />
              </Button>
            </TooltipTrigger>
            <TooltipContent>View snapshot</TooltipContent>
          </Tooltip>

          <IfCapable capability={Capability.BILLING_GENERATE}>
            {r.status === BillingStatus.GENERATED && (
              <>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => setAction({ export: r, status: BillingStatus.FINALIZED })}
                      aria-label={`Finalise billing snapshot v${r.billingVersion}`}
                      className="text-tone-success"
                    >
                      <CircleCheckIcon />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Finalise</TooltipContent>
                </Tooltip>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => setAction({ export: r, status: BillingStatus.CANCELLED })}
                      aria-label={`Cancel billing snapshot v${r.billingVersion}`}
                      className="text-tone-danger"
                    >
                      <CircleXIcon />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Cancel</TooltipContent>
                </Tooltip>
              </>
            )}
          </IfCapable>
        </RowActions>
      ),
    },
  ];

  async function confirmStatusChange(): Promise<void> {
    if (!action) return;
    try {
      await updateStatus.mutateAsync({ id: action.export.id, status: action.status });
      notify.success(
        `Billing export ${action.status === BillingStatus.FINALIZED ? 'finalised' : 'cancelled'}.`,
      );
      setAction(null);
    } catch (err) {
      notify.fromError(err);
      setAction(null);
    }
  }

  return (
    <>
      <PageHeader
        title="Billing"
        subtitle="Immutable snapshots of completed work. Generating one never alters an earlier export."
      />
      <ListToolbar
        search=""
        onSearchChange={() => {}}
        hideSearch
        activeFilterCount={status ? 1 : 0}
        onClearFilters={() => {
          setStatus('');
          setPage(1);
        }}
        filters={
          <SelectField
            label="Status"
            value={status}
            onChange={(v) => {
              setStatus(v as BillingStatus | '');
              setPage(1);
            }}
            emptyLabel="All statuses"
            options={enumOptions(BillingStatus)}
          />
        }
        view={view}
        onViewChange={setView}
        page={page}
        pageSize={pageSize}
        total={data?.meta.total ?? 0}
        onPageChange={setPage}
        onPageSizeChange={(size) => {
          setPageSize(size);
          setPage(1);
        }}
        onCreate={() => setGenerating(true)}
        createLabel="Generate Billing"
      />

      {view === 'table' ? (
        <DataTable
          gridId="billing"
          columns={columns}
          rows={data?.items ?? []}
          getRowId={(r) => r.id}
          loading={isLoading}
          onRowDoubleClick={(r) => setViewing(r.id)}
          filtered={Boolean(status)}
          emptyTitle="No billing exports yet"
          emptyMessage="Generate one to snapshot a period's completed orders."
          emptyAction={{ label: 'Generate billing', onClick: () => setGenerating(true) }}
        />
      ) : (
        <EntityCardGrid
          rows={data?.items ?? []}
          getRowId={(r) => r.id}
          loading={isLoading}
          onCardDoubleClick={(r) => setViewing(r.id)}
          filtered={Boolean(status)}
          emptyTitle="No billing exports yet"
          emptyMessage="Generate one to snapshot a period's completed orders."
          emptyAction={{ label: 'Generate billing', onClick: () => setGenerating(true) }}
          renderCard={(r) => (
            <div className="flex h-full flex-col gap-2.5">
              <div className="flex items-center justify-between gap-2">
                <Badge variant="secondary">Version {r.billingVersion}</Badge>
                <StatusChip status={r.status} />
              </div>
              <p className="text-[0.9375rem] leading-snug font-semibold">
                {r.periodFrom} → {r.periodTo}
              </p>
              <div className="mt-auto flex gap-6 pt-1">
                <div>
                  <p className="text-lg leading-tight font-bold tabular-nums">{r.totalOrders}</p>
                  <p className="text-muted-foreground text-xs">orders</p>
                </div>
                <div>
                  <p className="text-lg leading-tight font-bold tabular-nums">{r.totalPax}</p>
                  <p className="text-muted-foreground text-xs">pax</p>
                </div>
              </div>
            </div>
          )}
        />
      )}

      <GenerateBillingModal open={generating} onClose={() => setGenerating(false)} />
      <SnapshotViewerModal billingId={viewing} onClose={() => setViewing(null)} />

      <ConfirmDialog
        open={Boolean(action)}
        title={
          action?.status === BillingStatus.FINALIZED
            ? 'Finalise billing export'
            : 'Cancel billing export'
        }
        message={
          action?.status === BillingStatus.FINALIZED
            ? `Finalise version ${action?.export.billingVersion}? This confirms the snapshot as the record of billing for the period.`
            : `Cancel version ${action?.export.billingVersion}? The snapshot itself is never deleted, only marked cancelled.`
        }
        confirmLabel={action?.status === BillingStatus.FINALIZED ? 'Finalise' : 'Cancel export'}
        danger={action?.status === BillingStatus.CANCELLED}
        loading={updateStatus.isPending}
        onConfirm={confirmStatusChange}
        onCancel={() => setAction(null)}
      />
    </>
  );
}
