import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Spinner } from '@/components/ui/spinner';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Modal } from '../../components/Modal/Modal';
import { useBillingSnapshot } from '../../hooks/useAdmin';
import { StatusChip } from '../../components/StatusChip';

function Fact({ label, children }: { label: string; children: React.ReactNode }): JSX.Element {
  return (
    <p className="text-sm">
      <span className="text-muted-foreground">{label}:</span> {children}
    </p>
  );
}

export function SnapshotViewerModal({
  billingId,
  onClose,
}: {
  billingId: string | null;
  onClose: () => void;
}): JSX.Element {
  const { data, isLoading } = useBillingSnapshot(billingId ?? undefined);

  return (
    <Modal
      id="billing-snapshot"
      title="Billing snapshot"
      open={Boolean(billingId)}
      onClose={onClose}
      minWidth={640}
      minHeight={480}
      footer={
        <Button variant="outline" onClick={onClose}>
          Close
        </Button>
      }
    >
      {isLoading || !data ? (
        <div className="flex items-center gap-2 p-4 text-sm">
          <Spinner />
          Loading snapshot…
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <div className="flex flex-wrap gap-x-6 gap-y-1">
            <Fact label="Version">{data.billingVersion}</Fact>
            <Fact label="Period">
              {data.periodFrom} → {data.periodTo}
            </Fact>
            <Fact label="Generated by">{data.generatedBy}</Fact>
            <Fact label="Generated at">{new Date(data.generatedAt).toLocaleString()}</Fact>
          </div>

          <Separator />

          {data.orders.map((order) => (
            <div key={order.orderId} className="flex flex-col gap-2 border-b pb-4 last:border-b-0">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-semibold">{order.orderNumber}</span>
                <StatusChip status={order.status} />
                <span className="text-muted-foreground text-sm">
                  {order.boardName} · {order.venue} · pax {order.pax}
                </span>
              </div>

              {/* The item table scrolls inside its own frame — a snapshot with long item
                  names must never make the whole dialog scroll sideways. */}
              <div className="overflow-x-auto rounded-md border">
                <Table>
                  <TableHeader>
                    <TableRow className="hover:bg-transparent">
                      <TableHead>Category</TableHead>
                      <TableHead>Item</TableHead>
                      <TableHead className="text-right">Qty</TableHead>
                      <TableHead>Unit</TableHead>
                      <TableHead>Notes</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {order.items.map((item, idx) => (
                      <TableRow key={`${order.orderId}-${idx}`}>
                        <TableCell>{item.categoryName}</TableCell>
                        <TableCell>{item.itemName}</TableCell>
                        <TableCell className="text-right tabular-nums">{item.quantity}</TableCell>
                        <TableCell>{item.unit}</TableCell>
                        <TableCell>{item.notes ?? '—'}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </div>
          ))}

          {data.orders.length === 0 && (
            <p className="text-muted-foreground text-sm">No orders in this snapshot.</p>
          )}
        </div>
      )}
    </Modal>
  );
}
